# Generated by Django 4.1.4 on 2022-12-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDescriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name="Descriptions",
            new_name="JobDescriptions",
        ),
        migrations.AlterField(
            model_name="projects",
            name="descriptions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="resumes.projectdescriptions",
            ),
        ),
    ]
