# Generated by Django 4.1.4 on 2022-12-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_projdescriptions_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobDescriptions",
            new_name="JobDescription",
        ),
        migrations.RenameModel(
            old_name="ProjDescriptions",
            new_name="ProjDescription",
        ),
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
