# Generated by Django 4.1.4 on 2022-12-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_rename_jobdescriptions_jobdescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="resume",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skillset",
                to="resumes.resume",
            ),
        ),
    ]
